# Generated by Django 3.0.5 on 2020-05-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='account/img/3cc331d8-0848-4945-a068-12b3581dbcf8/'),
        ),
    ]
