# Generated by Django 3.0.5 on 2020-05-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200510_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='account/img/09056f88-f65b-403f-9678-61350b043181/'),
        ),
    ]
