# Generated by Django 3.0.5 on 2020-05-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200510_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='account/img/d7b969bb-b96c-494d-8782-7e88a3e23360/'),
        ),
    ]
