# Generated by Django 3.0.5 on 2020-05-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200510_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='account/img/d537a777-ac6d-4b35-8261-02fbd0e8d6bd/'),
        ),
    ]
