# Generated by Django 3.0.5 on 2020-05-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200510_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='account/img/e3a9158c-7757-4b98-94bb-92969989ba9d/'),
        ),
    ]
