# Generated by Django 3.0.5 on 2020-05-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200510_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='account/img/9e4615ef-5101-4bb9-b23f-f7d34a8ddc33/'),
        ),
    ]
