# Generated by Django 3.0.5 on 2020-05-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200510_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='account/img/e9b88522-aef8-4b57-b823-20b9fac0bf17/'),
        ),
    ]
