# Generated by Django 3.0.5 on 2020-05-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200510_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='account/img/e1d63d70-e7f1-46b8-a363-40f08aa06ebb/'),
        ),
    ]
