version: '3'

services:
  db:
    image: postgres:12.2
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=DarthVader
      - POSTGRES_PASSWORD=DeathStar
  web:
    container_name: online_store
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/online_store
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db

