version: '3'

services:

  web:
    container_name: online_store
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/online_store
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - neti

  db:
    image: postgres:12.2
    restart: always
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=DarthVader
      - POSTGRES_PASSWORD=DeathStar
    networks:
      neti:
        aliases:
        - neti_heki

networks:
  neti: